### PR TITLE
Added CryptoGround links.

### PR DESCRIPTION
**Pull request by evivz**
Added CryptoGround links.

### CODE REVIEW

**Comment by alexanderisora** [comment]
Hello and thanks for your interest. Sorry, can't add your resource at the moment:
your magazine looks amateur and you do not care about its quality. You have this big pictures (https://www.cryptoground.com/storage/images/posts/1526294830-1.jpg) on your main page and it's loading very slowly.

Lots of 💖,
Alex.

P.S.: Welcome to the new Bitcoin forum: https://cryptoheresy.com/
Feel free to create a thread about your resource!

**Comment by alexanderisora** [comment]
Hi again @evivz   🙂
Just wanted to tell you that I've launched a **marketplace of rare crypto-related domains, websites and social profiles**. You can buy and sell items (it's free).

Welcome https://opencrypto.space/

**Comment by evivz** [comment]
Can you look out at our site once again? We have reworked on images and our
home page is now less than 1.5-2 MB.
Compared with all major sites our load time is fastest.

**Comment by alexanderisora** [comment]
@evivz I've added CryptoGround 👍 
P.S.: have you checked https://opencrypto.space/?

**Comment by evivz** [comment]
This looks cool. I have few domains for sale if you wish you can add them
blocktoro.com cryptoblock.pub cryptoblockpub.com

**Comment by alexanderisora** [comment]
Glat you liked it @evivz 👍 
Please submit your domains here: https://opencrypto.space/sell-domain and they will appear on the site.

**Pull request closed without merging**
