### PR TITLE
Add cryptojacking article

### PR DESCRIPTION
**Pull request by dailymorn**

### CODE REVIEW

**Comment by alexanderisora** [comment]
Hello @dailymorn !
Thanks for your PR. Sorry, but I can not accept it because you have posted an article and it's a tools' list. Thanks.

P.S.: Make sure to read the Cointributor's guide: https://github.com/coinpride/CryptoList/blob/master/CONTRIBUTING.md

**Comment by dailymorn** [comment]
Do you mean the MIning section is a tools list?

I wasn't sure if the Mining section (article is about secret mining) and the Learning > Other section would be more useful. Do you think it might serve your audience better over there?

(BTW, one of the guides in that section is doing cryptojacking.)

**Comment by alexanderisora** [comment]
Hey @dailymorn! 👋
CryptoList is supposed to be the list of _tools_ and _resources_. Tools and resources like media, Youtube channels, price tracking services, you know. Those type of things can be used many times, they are evolving. 
Articles are static. Ideas in (most) articles die. 

I think an opensourced list of cool articles/reads would be so useful and loved by the crowd. What do you think?

**Comment by dailymorn** [comment]
Yes, that would probably be useful.
I understand the tools/resources vs. articles distinction now. Thanks for explaining.

**Comment by alexanderisora** [comment]
Hi again @dailymorn   🙂
Just wanted to tell you that I've launched a **marketplace of rare crypto-related domains, websites and social profiles**. You can buy and sell items (it's free).

Welcome https://opencrypto.space/

**Pull request closed without merging**
