### PR TITLE
Add CryptoAudio as news aggregator

### PR DESCRIPTION
**Pull request by francescomalatesta**
Hi there!

Added CryptoAudio, a totally free tool that creates news summaries from various sources and reads them using a text-to-speech technology. I created it to practice with some AWS technologies.

http://cryptoaud.io

### CODE REVIEW

**Comment by waldbach** [comment]
Sorry to interrupt, just wanted to let you know I shared this in a Facebook group as well: https://www.facebook.com/groups/516291715400209/

Good product!

**Comment by francescomalatesta** [comment]
Any news @coinpride ? :) Do you think it's a good resource?

**Comment by alexanderisora** [comment]
@francescomalatesta nice one, bro. Added!
Feel free to create a dedicated topic about your tool on my forum: https://cryptoheresy.com/
I will bring visitors to check it 🙂

**Comment by alexanderisora** [comment]
Hi again @francescomalatesta   🙂
Just wanted to tell you that I've launched a **marketplace of rare crypto-related domains, websites and social profiles**. You can buy and sell items (it's free).

Welcome https://opencrypto.space/

**Pull request merged**
