### PR TITLE
Add CRYPTOFINANCE Google Sheets add-on.

### PR DESCRIPTION
**Pull request by nepsilon**
Adding [CRYPTOFINANCE](https://chrome.google.com/webstore/detail/cryptofinance/bhjnahcnhemcnnenhgbmmdapapblnlcn) Google Sheets add-on.

### CODE REVIEW

**Comment by alexanderisora** [comment]
Hello @nepsilon!
Thanks for your interest in the project and the Pull Request 🙂
Sorry, but I can not accept your PR because you've added it to the top. And it's not even a tool, but an article. 

I will add the sheet in the right place.

P.S.: Make sure to read the Contributor's guide: https://github.com/coinpride/CryptoList/blob/master/CONTRIBUTING.md

**Comment by nepsilon** [comment]
Hi @alexanderisora, thanks.

"Intelligent power up for Google Sheets" is not a good description for the tool. Can we keep the one I wrote?
"Google Sheets add-on to get cryptocurrencies rate and other data directly in your spreadsheet"

The link I used is the documentation. Google Sheets make it hard to find the documentation when a user starts from the webstore. Can we revert the link to original too? I'd like to avoid to answer too many support questions about the documentation and how to use the add-on.

**Comment by alexanderisora** [comment]
@nepsilon CryptoList is supposed to be a list of tools, not articles or docs. 
If you will create a landing page with two buttons 'read docs' and 'install' I will add it.
But now, I can keep only the extension link. I can remove it if you it makes problems for you.

Thanks for understanding.

P.S.: I've changed the description.

**Comment by alexanderisora** [comment]
Hi again @nepsilon   🙂
Just wanted to tell you that I've launched a **marketplace of rare crypto-related domains, websites and social profiles**. You can buy and sell items (it's free).

Welcome https://opencrypto.space/

**Comment by nepsilon** [comment]
Just submitted one

**Comment by nepsilon** [comment]
BTW, could you update my link to the add-on website now? The new website is http://cryptofinance.jbuty.com . Thanks!

**Comment by alexanderisora** [comment]
@nepsilon updated!
Btw, Nepsilon, could you give some feedback on https://opencrypto.space/ please? It would help me a lot!

**Comment by nepsilon** [comment]
Thanks for the update.

As for feedback, the value proposition is clear and it's a good niche to target. The implementation of the idea is clean, easy to find what we want to do (buy/sell). Good idea to re-enforce the value prop at the bottom of the page. Now just need to push the message to different the marketing channels and maybe find partnerships. Seem you're already doing that 👍

**Pull request closed without merging**
