### PR TITLE
Add cryptomonitor.trade to README.md

### PR DESCRIPTION
**Pull request by lenilsonjr**
Adding (my own) simple progressive web app to track prices and profits.

### CODE REVIEW

**Comment by alexanderisora** [comment]
Sorry, @lenilsonjr buddy.
Your product looks and works awful. There are many more strong analogs. I can't add it.
image

**Comment by lenilsonjr** [comment]
¯\_(ツ)_/¯

**Comment by lenilsonjr** [comment]
¯\\\_(ツ)_/¯

**Comment by lenilsonjr** [comment]
Thanks for the feedback anyway. It was designed to suit my own needs and I really didn't put much thought on UI/UX.

I'll try to make some improvements and see if I can make it good enough.

**Comment by alexanderisora** [comment]
Hi again @lenilsonjr   🙂
Just wanted to tell you that I've launched a **marketplace of rare crypto-related domains, websites and social profiles**. You can buy and sell items (it's free).

Welcome https://opencrypto.space/

**Pull request closed without merging**
